### ISSUE TITLE
Validators not run for Form controller checkboxes and radios

### ISSUE THREAD

**Issue by mxposed** [addrummond/ibex#24]
I don't know if that's the design, but we currently need to validate radio-button answers and stumbled upon this

**Comment by addrummond** [comment]
@mxposed I'm focusing on the Ibex Farm rather than Ibex right now, but pull requests welcome for this issue. You'd want to take a look at https://github.com/addrummond/ibex/blob/a550fe86676aa8f0e3511efbea1acb798bf2acfb/js_includes/Form.js#L72 and ensure that the validators also get called for checkboxes/radio buttons.
